---
- name: Check repository exists
  shell: |
    aws ecr describe-repositories --repository-names {{ ecr_repository_name }}
  register: check_repository_exists
  failed_when: false
  changed_when: check_repository_exists.rc != 0

- name: Create repository
  shell: |
    aws ecr create-repository --repository-name {{ ecr_repository_name }} --region {{ aws_region }}
  register: create_repository
  failed_when: false
  changed_when: create_repository.rc != 0
  when: check_repository_exists is defined and check_repository_exists.rc != 0
  tags: create_repository_tag

- fail:
    msg: "Failed to create repository"
  when: create_repository is defined and
    (create_repository.rc is defined and create_repository.rc != 0)

- name: Authenticate Docker with ECR
  shell: "$(aws ecr get-login --no-include-email --region {{ aws_region }})"

- name: Build Docker image
  shell: "docker build -t {{ ecr_repository_name }}:latest ."

- name: Tag Docker image
  shell: "docker tag {{ ecr_repository_name }}:latest {{ ecr_repository_registry }}/{{ ecr_repository_name }}>:latest"

- name: Push Docker image to ECR
  shell: "docker push {{ ecr_repository_registry }}/{{ ecr_repository_name }}:latest"