---
- name: Add an apt signing key for docker
  apt_key:
    url: "{{ google_apt_key }}"
    state: present

#- name: Add repository for docker
#  apt_repository:
#    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
#    state: present

- name: Update apt cache
  apt:
    name: aptitude
    state: latest
    update_cache: true
    force_apt_get: true

- name: Check docker version
  shell: docker version
  register: check_docker_version
  failed_when: false
  changed_when: check_docker_version.rc != 0

- debug:
    msg: "{{ check_docker_version.stdout }}"

- name: Install docker.io
  package:
    name: docker.io
    state: latest
  ignore_errors: true
  when: check_docker_version is undefined or check_docker_version.rc != 0

- name: Create {{ deployment_cicd_dir }}
  file:
    path: "{{ deployment_cicd_dir }}"
    state: directory

- name: Download cri-dockerd
  get_url:
    url: "https://github.com/Mirantis/cri-dockerd/releases/download/v{{ cri_docker_version }}/cri-dockerd_{{ cri_docker_version }}.3-0.ubuntu-jammy_amd64.deb"
    dest: "{{ deployment_cicd_dir }}"

- name: Install cri-dockerd
  apt:
    deb: "{{ deployment_cicd_dir }}/cri-dockerd_{{ cri_docker_version }}.3-0.ubuntu-jammy_amd64.deb"

- name: Add user to docker group
  command: usermod -aG docker $USER
  register: add_docker_group
  failed_when: false
  changed_when: add_docker_group.rc != 0

- name: Config docker service
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
    line: 'ExecStart=/usr/bin/dockerd -H fd://'
    backrefs: true

- name: Remove containerd socket
  file:
    path: "/run/containerd"
    state: absent

- name: Enable docker service
  systemd:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true

- name: Enable cri-dockerd
  systemd:
    state: restarted
    daemon_reload: true
    name: cri-docker
    enabled: true