---

- name: Install docker
  include_tasks: docker.yml
  tags: install_docker

- name: Remove {{ deployment_cicd_dir }}
  file:
    path: "{{ deployment_cicd_dir }}"
    state: absent

- name: Create {{ deployment_cicd_dir }} if not exists
  file:
    path: "{{ deployment_cicd_dir }}"
    state: directory
    owner: "{{ username | default(ansible_user) }}"
    group: "{{ username | default(ansible_user) }}"
    mode: 0755
