pipeline {
    agent any

    stages {
        stage('Checkout'){
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                browser: github('https://github.com/phongnghia/devops-test.git'),
                extensions: [],
                userRemoteConfigs: [[url: 'https://github.com/phongnghia/devops-test.git']])
            }
        }
        stage('Build') {
            steps {
                //sh 'dpkg --configure -a;apt-get install -f'
                //sh 'apt-get update;apt-get install -y python3'
                //sh 'python3 -m pip install --upgrade pip; pip3 install ansible boto3'
                sh 'cp /var/lib/jenkins/token.txt .'
                sh 'ansible-playbook deploy-docker/install.yml --skip-tags "build_stage,deployment_stage"'
                sh 'ansible-playbook deploy-docker/install.yml --skip-tags "pre_setup_stage,deployment_stage" --extra-vars "dockerhub_username=$DOCKERHUB_USERNAME"'
            }
        }
        stage('Validation') {
            steps {
                sh 'ansible-playbook deploy-docker/install.yml --skip-tags "build_stage,deployment_stage"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'ansible-playbook deploy-docker/install.yml --skip-tags "build_stage,deployment_stage"'
            }
        }
    }
}
