- name: Test devops-test Image
  hosts: localhost
  become: true
  vars_files:
    - vars/defaults.yml
  tasks:
    - name: Pull devops-test image
      shell: docker pull {{ ecr_repository_registry }}/{{ ecr_repository_name }}:latest
      register: pull_image
      failed_when: false
      changed_when: pull_image.rc != 0

    - name: Run Container
      shell: docker run --name devops-test -d --entrypoint bash {{ ecr_repository_registry }}/{{ ecr_repository_name }}:latest ./run.sh
      register: run_test_container

    - name: Check if container is running
      shell: docker inspect -f '{{ "{{ .State.Running }}" }}' {{ run_test_container.stdout }}
      register: container_is_running

    - name: Fail if container did not start
      fail:
        msg: "Container failed to start"
      when: container_is_running.stdout != "true"

    - name: Add pytest
      shell: docker exec {{ run_test_container.stdout }} poetry add --dev pytest
      register: add_pytest
      failed_when: false
      changed_when: add_pytest.rc != 0

    - fail:
        msg: "{{ add_pytest.stderr_lines }}"
      when: add_pytest.rc is defined and add_pytest.rc != 0

    - name: Run tests
      shell: docker exec {{ run_test_container.stdout }} poetry run pytest -s
      register: test_execute_result

    - name: Remove container
      shell: docker rm -f {{ run_test_container.stdout }}
      when: test_execute_result is defined

    - name: Fail if Tests Failed
      fail:
        msg: "Tests failed."
      when: test_execute_result.rc != 0

    - name: Test Passed
      debug:
        msg: |
          Test Passed:
          {{ test_execute_result.stdout_lines }}