---

- name: Create {{ deployment_cicd_dir }} if not exists
  file:
    path: "{{ deployment_cicd_dir }}"
    state: directory
    owner: "{{ username | default(ansible_user) }}"
    group: "{{ username | default(ansible_user) }}"
    mode: 0755

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ deployment_cicd_dir }}/docker-compose.yml"

- name: Deployment devops-test application
  shell: docker compose up



